name = "GIV"
uuid = "bf339e5b-51e6-4b7b-82b3-758165633231"
authors = ["Fu Zhiyu"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
